#!/usr/bin/env python
# coding: utf-8

# In[6]:


import IPython
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')
from country_converter import CountryConverter
from IPython.display import display


# In[7]:


cc = CountryConverter()


# In[8]:


file_path = r"C:\Users\Hp\Downloads\dataset.xlsx"
df = pd.read_excel(file_path)


# In[9]:


df.head()


# In[10]:


revenue_by_client = df.groupby('Beneficial User')['Buy Margin (£)'].sum()


# In[11]:


highest_revenue_client = revenue_by_client.idxmax()
highest_revenue_amount = revenue_by_client.max()


# In[12]:


print("Client with the highest revenue:", highest_revenue_client)
print("Revenue generated by the client:", highest_revenue_amount)


# In[13]:


revenue_by_operator = df.groupby('Operator')['Buy Margin (£)'].sum()


# In[14]:


highest_revenue_operator = revenue_by_operator.idxmax()
highest_revenue_amount = revenue_by_operator.max()


# In[15]:


print("Operator with the highest revenue:", highest_revenue_operator)
print("Revenue generated by the operator:", highest_revenue_amount)


# In[16]:


revenue_by_client = df.groupby('Beneficial User')['Buy Margin (£)'].sum()


# In[17]:


top_client = revenue_by_client.idxmax()
top_client_revenue = revenue_by_client.max()


# In[18]:


print("Top client in terms of revenue:", top_client)
print("Revenue generated by the top client:", top_client_revenue)


# In[19]:


total_revenue = df['Buy Margin (£)'].sum()


# In[20]:


percentage_contribution = (top_client_revenue / total_revenue) * 100


# In[21]:


print("Percentage of revenue contributed by the top client: {:.2f}%".format(percentage_contribution))


# In[22]:


revenue_by_client = df.groupby('Beneficial User')['Buy Margin (£)'].sum()


# In[23]:


top_10_clients = revenue_by_client.sort_values(ascending=False).head(10)


# In[24]:


print("Top 10 clients:")
print(top_10_clients)


# In[25]:


if not pd.api.types.is_datetime64_any_dtype(df['Date']):
    df['Date'] = pd.to_datetime(df['Date'])


# In[26]:


revenue_by_date = df.groupby('Date')['Buy Margin (£)'].sum()


# In[27]:


date_with_highest_revenue = revenue_by_date.idxmax()


# In[28]:


total_revenue = df['Buy Margin (£)'].sum()
percentage_contribution = (revenue_by_date[date_with_highest_revenue] / total_revenue) * 100


# In[30]:


print("Date with the highest revenue:", date_with_highest_revenue)
print("Percentage contribution of the day's revenue: {:.2f}%".format(percentage_contribution))


# In[35]:


plt.figure(figsize=(12, 6))
revenue_by_date.plot(kind='bar', color='Orange', edgecolor='black', linewidth=0.7)
plt.axvline(x=date_with_highest_revenue, color='firebrick', linestyle='--', label='Day with Highest Revenue')
plt.title('Daily Revenue Analysis', fontsize=16, fontweight='bold')
plt.xlabel('Date', fontsize=12)
plt.ylabel('Revenue (£)', fontsize=12)
plt.xticks(fontsize=10, rotation=45, ha='right')
plt.yticks(fontsize=10)
plt.legend(fontsize=10)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()


# In[45]:


revenue_by_operator = df.groupby('Operator')['Buy Margin (£)'].sum()


# In[46]:


operator_with_max_revenue = revenue_by_operator.idxmax()


# In[47]:


operator_with_max_revenue = revenue_by_operator.idxmax()


# In[48]:


print("Operator with the highest revenue:", operator_with_max_revenue)


# In[49]:


sorted_revenue = revenue_by_operator.sort_values(ascending=False)


# In[50]:


top_10_operators = sorted_revenue.head(10)


# In[53]:


plt.figure(figsize=(12, 6))
top_10_operators.plot(kind='bar', color='orange', edgecolor='black')
plt.title('Top 10 Operators with Highest Revenue')
plt.xlabel('Operator')
plt.ylabel('Revenue (£)')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()


# In[57]:


df['Continent'] = df['Operator Country'].apply(lambda country: cc.convert(names=country, to='continent'))


# In[63]:


df['Profit'] = df['User Amount (£)'] - df['Calculated Cost (£)']


# In[65]:


revenue_breakdown = df.groupby(['Operator', 'Operator Country', 'Continent', 'Operator Currency'])['Profit'].sum().reset_index()


# In[68]:


revenue_breakdown = revenue_breakdown.sort_values(by='Profit', ascending=False)


# In[69]:


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)


# In[70]:


#print(revenue_breakdown)
display(revenue_breakdown)


# In[80]:


product_revenue = df.groupby('Product Name')['Buy Margin (£)'].sum().reset_index()


# In[81]:


least_performing_products = product_revenue.sort_values(by='Buy Margin (£)', ascending=True)


# In[82]:


top_10_least_performing_products = least_performing_products.head(10)


# In[83]:


print("Top 10 Least Performing Products:")
print(least_performing_products)


# In[85]:


plt.figure(figsize=(12, 6))
plt.bar(top_10_least_performing_products['Product Name'], top_10_least_performing_products['Buy Margin (£)'], color='Orange')
plt.title('Top 10 Least Performing Products')
plt.xlabel('Product Name')
plt.ylabel('Buy Margin (£)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()


# In[ ]:




